 /*
  Cars Action
 */

export const FETCHING_CARS = "FETCHING_CARS";
export const FETCHING_CARS_SUCCEDDED = "FETCHING_CARS_SUCCEDDED";
export const FETCHING_CARS_FAILED = "FETCHING_CARS_FAILED";

export const SEARCHING_CARS = "SEARCHING_CARS";
export const SEARCHING_CARS_SUCCEDDED = "SEARCHING_CARS_SUCCEDDED";
export const SEARCHING_CARS_FAILED = "SEARCHING_CARS_FAILED";