/*
  Anonymous Actions
*/
export const AUTHENTICATING_USER = "AUTHENTICATING_USER";
export const AUTHENTICATING_USER_SUCCEDDED = "AUTHENTICATING_USER_SUCCEDDED";
export const AUTHENTICATING_USER_FAILED = "AUTHENTICATING_USER_FAILED";

export const AUTHENTICATING_USER_REQUEST = "AUTHENTICATING_USER_REQUEST";
export const AUTHENTICATING_USER_REQUEST_SUCCEDDED =
  "AUTHENTICATING_USER_REQUEST_SUCCEDDED";
export const AUTHENTICATING_USER_REQUEST_FAILED =
  "AUTHENTICATING_USER_REQUEST_FAILED";


 /*
  Cars Action
 */

  export const FETCHING_CARS = "FETCHING_CARS";
  export const FETCHING_CARS_SUCCEDDED = "FETCHING_CARS_SUCCEDDED";
  export const FETCHING_CARS_FAILED = "FETCHING_CARS_FAILED";
  
  export const SEARCHING_CARS = "SEARCHING_CARS";
  export const SEARCHING_CARS_SUCCEDDED = "SEARCHING_CARS_SUCCEDDED";
  export const SEARCHING_CARS_FAILED = "SEARCHING_CARS_FAILED";  